services:

  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./appdata:/data
      - ./letsencrypt:/etc/letsencrypt

  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    volumes:
      - ./appdata:/config
    ports:
      - 8080:8080
    restart: unless-stopped

  roundcubemail:
    image: roundcube/roundcubemail:latest
    container_name: roundcubemail
    volumes:
      - ./appdata:/var/www/html
      - ./appdata/db/sqlite:/var/roundcube/db
    ports:
      - 8443:8443
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://imap.uni-muenster.de
      - ROUNDCUBEMAIL_DEFAULT_PORT=993
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://secmail.uni-muenster.de
      - ROUNDCUBEMAIL_SMTP_PORT=587
