services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - roundcubemail
      - dokuwiki
    networks:
      - app-network

  roundcubemail:
    image: roundcube/roundcubemail:latest
    container_name: roundcubemail
    volumes:
      - ./www:/var/www/html
      - ./db/sqlite:/var/roundcube/db
    ports:
      - 9002:80
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://imap.uni-muenster.de
      - ROUNDCUBEMAIL_DEFAULT_PORT=993
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://secmail.uni-muenster.de
      - ROUNDCUBEMAIL_SMTP_PORT=587
    networks:
      - app-network

  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    volumes:
      - ./www/var/www/dokuwiki/config:/config
    ports:
      - 9000:80
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
