services:

apache:
    image: httpd:latest
    container_name: apache
    ports:
    - '80:80'
    volumes:
    - ./appdata/apache/website:/usr/local/apache2/htdocs

  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    volumes:
      - ./appdata/dokuwiki:/config
    ports:
      - 8080:8080
    restart: unless-stopped

  roundcubemail:
    image: roundcube/roundcubemail:latest
    container_name: roundcubemail
    volumes:
      - ./appdata/roundcube:/var/www/html
      - ./appdata/roundcube/db/sqlite:/var/roundcube/db
    ports:
      - 8443:8443
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://imap.uni-muenster.de
      - ROUNDCUBEMAIL_DEFAULT_PORT=993
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://secmail.uni-muenster.de
      - ROUNDCUBEMAIL_SMTP_PORT=587
